<?php

use Illuminate\Database\Seeder;

class GoodsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("goods")
            ->insert([
                [
                    'good_name' => '3v4a0L',
                    'good_producer' => 'HrmH99HU63',
                    'good_publisher' => 'za9aRMVnuQ',
                    'good_price' => 91124,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'M9ZAQN',
                    'good_producer' => '9AVaqiBnBq',
                    'good_publisher' => '6linKdQQNE',
                    'good_price' => 83038,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'iV3kXf',
                    'good_producer' => 'ASgG7zoc3W',
                    'good_publisher' => '1iFKAfhOnP',
                    'good_price' => 77912,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'nIbB5Y',
                    'good_producer' => 'cMDtPytp1z',
                    'good_publisher' => 'E1VXyTvc8J',
                    'good_price' => 16635,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'BbPg9n',
                    'good_producer' => '4ludwuvvuL',
                    'good_publisher' => '7askyw5eqi',
                    'good_price' => 70147,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'O1GGxn',
                    'good_producer' => 'OzuKLe0QNo',
                    'good_publisher' => 'GIdbpvntp7',
                    'good_price' => 92472,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'NuqsAV',
                    'good_producer' => 'kOyNuiNhxG',
                    'good_publisher' => '9Jrz77u1DB',
                    'good_price' => 97547,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'MXjNL6',
                    'good_producer' => 'ifvx7KF1HU',
                    'good_publisher' => 'yacMjPhVry',
                    'good_price' => 38155,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'XzcuGv',
                    'good_producer' => 'DuU6uRJ2PN',
                    'good_publisher' => '3iAMDDvYq3',
                    'good_price' => 69665,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'X4QLut',
                    'good_producer' => 'hUQDmRknPe',
                    'good_publisher' => 'zuSRWkSvVR',
                    'good_price' => 991,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'zP5G2c',
                    'good_producer' => 'lRG5SCrjaE',
                    'good_publisher' => 'UpiXfiOGhb',
                    'good_price' => 1790,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'QRxDD9',
                    'good_producer' => 'mkCvYaVcmM',
                    'good_publisher' => '30OjTvhVqn',
                    'good_price' => 41211,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'yqR3bL',
                    'good_producer' => 'LaB9HfwFND',
                    'good_publisher' => '953Rzd86En',
                    'good_price' => 70395,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'RpWdE5',
                    'good_producer' => 'gO75A0pSbu',
                    'good_publisher' => 'DE39U1CrJc',
                    'good_price' => 52796,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'LqvNyf',
                    'good_producer' => 'OwAE7yFSv1',
                    'good_publisher' => '77v0gcHHv6',
                    'good_price' => 81856,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'oHhyfB',
                    'good_producer' => 'HXRF7H2uwg',
                    'good_publisher' => 'BlE2quU6Fi',
                    'good_price' => 61661,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'OdXqos',
                    'good_producer' => 'aifRCeWpDG',
                    'good_publisher' => '1QuIMGMuGs',
                    'good_price' => 40198,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '1zRQD6',
                    'good_producer' => 'o9QQ53QqOw',
                    'good_publisher' => 'TQSVLpvk8N',
                    'good_price' => 99199,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'sOM4g9',
                    'good_producer' => 'onDCkfthEF',
                    'good_publisher' => '7QbBvuqwA7',
                    'good_price' => 19703,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'enuCpc',
                    'good_producer' => '97ZW1CB0MS',
                    'good_publisher' => 'Jzx1gA6SPq',
                    'good_price' => 72818,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'hmIRUf',
                    'good_producer' => 'kvG4lpt58y',
                    'good_publisher' => '4dCS9nvsaO',
                    'good_price' => 35621,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'ms59V7',
                    'good_producer' => 'RRt7Htwtlw',
                    'good_publisher' => 'jFr4iJxvlG',
                    'good_price' => 83787,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'yRGRb3',
                    'good_producer' => 'KVZRiAr7XT',
                    'good_publisher' => 'XDCwB6ntiZ',
                    'good_price' => 20544,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'Gx4whq',
                    'good_producer' => 'Riqtqt0Pza',
                    'good_publisher' => 'Co9idPgYV7',
                    'good_price' => 44659,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'yi7oQS',
                    'good_producer' => 'hMQeYMKn3v',
                    'good_publisher' => 'bNI0yUz434',
                    'good_price' => 18378,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'j7YvpX',
                    'good_producer' => 'iqMr3EuR68',
                    'good_publisher' => 'DvAfS0KuUQ',
                    'good_price' => 49780,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'hfOBX5',
                    'good_producer' => 'tTe0PaNYuB',
                    'good_publisher' => '6lklfMlAvE',
                    'good_price' => 61655,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '2hqXNM',
                    'good_producer' => 'JtnoodqEHJ',
                    'good_publisher' => 'SeMQrv8kSI',
                    'good_price' => 13742,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'iSjpVB',
                    'good_producer' => 'YTNQWrtVAi',
                    'good_publisher' => '0ztJLQC81u',
                    'good_price' => 38447,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'Zhvlnw',
                    'good_producer' => 'S9iPxfcTci',
                    'good_publisher' => 'zjXPXb0UoA',
                    'good_price' => 70785,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'Ytwxut',
                    'good_producer' => '5fDuspHjHz',
                    'good_publisher' => 'oD7qLTJUw5',
                    'good_price' => 11686,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'PnkpPY',
                    'good_producer' => 'DJ92TFhhhO',
                    'good_publisher' => 'MrSIkTYAXs',
                    'good_price' => 14942,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'OHg0td',
                    'good_producer' => 'zgBKeynd2X',
                    'good_publisher' => 'CUuWb7Wb0T',
                    'good_price' => 20982,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '4ZInmb',
                    'good_producer' => 'BxxFIvrSWX',
                    'good_publisher' => 'c6ZjY0SsCu',
                    'good_price' => 97942,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'vgeg2i',
                    'good_producer' => 'e3NvJXxlsW',
                    'good_publisher' => '3Ii6pDAs0u',
                    'good_price' => 92282,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'XUrqZv',
                    'good_producer' => 'zXA7ha4Utb',
                    'good_publisher' => 'xMWDBTOm6z',
                    'good_price' => 41751,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'gl0Aeh',
                    'good_producer' => 'tHyJWHMIL4',
                    'good_publisher' => 'WDmdxYe37j',
                    'good_price' => 35093,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'qM3DpT',
                    'good_producer' => '4yGxV1WZKk',
                    'good_publisher' => 'qUPRH1OTMC',
                    'good_price' => 90132,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'jbdEJt',
                    'good_producer' => 'jSotvppx28',
                    'good_publisher' => 'siAEmrKE6r',
                    'good_price' => 72599,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '1OlFXX',
                    'good_producer' => 'lmreZRjkiS',
                    'good_publisher' => 'voXkoPx0oB',
                    'good_price' => 6575,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '7OMvr6',
                    'good_producer' => 'JdpwTDoVTW',
                    'good_publisher' => 'PyOSta4BCs',
                    'good_price' => 44892,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'PfbQRB',
                    'good_producer' => 'vvxShDM8IK',
                    'good_publisher' => '2HKXWKhsqm',
                    'good_price' => 32649,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'mU3qtw',
                    'good_producer' => 'bxzLZoAZSG',
                    'good_publisher' => 'p0dUz1aS3V',
                    'good_price' => 26132,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '3gyf7v',
                    'good_producer' => 'nlUgokwQtN',
                    'good_publisher' => 'v8lTA9HlbN',
                    'good_price' => 96525,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'wCCvR5',
                    'good_producer' => 'UUbKiJ9emm',
                    'good_publisher' => 'EhfBDih6EA',
                    'good_price' => 83944,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'DqEFSL',
                    'good_producer' => 'ss4S6T3kQb',
                    'good_publisher' => 'hG16T1yYCS',
                    'good_price' => 28418,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'kZevqN',
                    'good_producer' => 'ap1i3267NZ',
                    'good_publisher' => '1EJNi18386',
                    'good_price' => 68226,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'ZFO0YR',
                    'good_producer' => 'evvOFdJBAy',
                    'good_publisher' => 'Nmk5tRReTC',
                    'good_price' => 23515,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'fYQiey',
                    'good_producer' => 'jqiSQ1qFxl',
                    'good_publisher' => 'iel9k7LQp7',
                    'good_price' => 63707,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'Q0G6KS',
                    'good_producer' => 'iYDLrGXU7i',
                    'good_publisher' => 'nWfc2wVeIG',
                    'good_price' => 21094,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '0DiveZ',
                    'good_producer' => 'CMrnVP8YjU',
                    'good_publisher' => 'tG53pPfupu',
                    'good_price' => 69300,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'UfIwZY',
                    'good_producer' => 'SUb4MhuyFA',
                    'good_publisher' => 'CQAst5usSe',
                    'good_price' => 17518,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'aTE2wO',
                    'good_producer' => '45f0eKgmjK',
                    'good_publisher' => 'EBcMtnjuLH',
                    'good_price' => 24977,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'zFbfkN',
                    'good_producer' => 'sYPFZC61PU',
                    'good_publisher' => 'm0wWvwsreD',
                    'good_price' => 52099,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'SXXZ6Z',
                    'good_producer' => 'aQ9t5Hnlkt',
                    'good_publisher' => 'o2fqoKwXDA',
                    'good_price' => 34395,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'yRyqSb',
                    'good_producer' => 'tOqHDhbGkL',
                    'good_publisher' => '3ykKjnMP84',
                    'good_price' => 60612,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'JPl8oN',
                    'good_producer' => 'dpmM8j4Xte',
                    'good_publisher' => 'FHUv4gkF3x',
                    'good_price' => 56369,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'lhYM8o',
                    'good_producer' => 'sOBkuWVflq',
                    'good_publisher' => 'PVNdK4ZMaQ',
                    'good_price' => 99864,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'TQ6QU7',
                    'good_producer' => 'udzaQ7daS0',
                    'good_publisher' => 'CgltDyUlYt',
                    'good_price' => 22722,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'BGMqu5',
                    'good_producer' => '5JP4zICUAw',
                    'good_publisher' => 'obuZABTOaG',
                    'good_price' => 15652,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'WFUaKj',
                    'good_producer' => 'gXqF0ZYp3p',
                    'good_publisher' => 'ngOBqVcc6K',
                    'good_price' => 21148,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'ECvL27',
                    'good_producer' => '4z47X2mvWX',
                    'good_publisher' => 'gt8Pf4ja9Q',
                    'good_price' => 50094,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'WhlIo8',
                    'good_producer' => 'SYcIP3io0B',
                    'good_publisher' => 'Zfuqd3II1S',
                    'good_price' => 98973,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'KCoayb',
                    'good_producer' => 'NXwEpdDk5M',
                    'good_publisher' => 'cfoCUtFiYI',
                    'good_price' => 63989,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'lmTThZ',
                    'good_producer' => '7vc3mjjagE',
                    'good_publisher' => 'yAroMUwSWa',
                    'good_price' => 92,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'tiEWcn',
                    'good_producer' => 'qrGe0lPFhW',
                    'good_publisher' => 'a7Z2pK4jWp',
                    'good_price' => 11284,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '7g9CG5',
                    'good_producer' => 'iW9AvvA8Dt',
                    'good_publisher' => 'I1b5FoQWpq',
                    'good_price' => 29668,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'yXhChM',
                    'good_producer' => '3ybjMlb8un',
                    'good_publisher' => '5royCIWRW2',
                    'good_price' => 70180,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'k2YWpu',
                    'good_producer' => 'coARDAhan9',
                    'good_publisher' => 'PFZJKcui2t',
                    'good_price' => 9638,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'D2ijNQ',
                    'good_producer' => '8KzUnE6R56',
                    'good_publisher' => 'oTmyngMpMJ',
                    'good_price' => 29485,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'YLfDg8',
                    'good_producer' => '9rdaB7fBje',
                    'good_publisher' => 'nE19L9EzZs',
                    'good_price' => 44193,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '1AeuC6',
                    'good_producer' => 'tlTQV7zMWM',
                    'good_publisher' => 'ExNANCAFzA',
                    'good_price' => 39704,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '8cyJSj',
                    'good_producer' => 'XZC4hlOIiR',
                    'good_publisher' => 'fhmeobjunB',
                    'good_price' => 58710,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'CTFeGz',
                    'good_producer' => 'TMOKcx6bKM',
                    'good_publisher' => 'YysHnUJdwN',
                    'good_price' => 66679,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'vpMgvz',
                    'good_producer' => 'eaB7h240pG',
                    'good_publisher' => 'cjcyJpWdfW',
                    'good_price' => 91999,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'FNqtDk',
                    'good_producer' => 'A65ivLplka',
                    'good_publisher' => 'fK48he76Sz',
                    'good_price' => 29811,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'sglNrg',
                    'good_producer' => 'Juy4g1FH78',
                    'good_publisher' => 'BNZIQFr0OD',
                    'good_price' => 28805,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'zNSuvo',
                    'good_producer' => 'SZar8dlOP9',
                    'good_publisher' => '8ymv0hZnWE',
                    'good_price' => 95448,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'dTLnUf',
                    'good_producer' => 'CfvK8fVQHd',
                    'good_publisher' => 'VrATxdjAf8',
                    'good_price' => 30762,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'agHHVQ',
                    'good_producer' => 'Xa3miU63Qj',
                    'good_publisher' => 'OBIVIiCWew',
                    'good_price' => 63789,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'XGhrUI',
                    'good_producer' => 'NnqGjIwLAA',
                    'good_publisher' => '3YJEqK4aOw',
                    'good_price' => 31648,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'iKs5L0',
                    'good_producer' => 'Ronb5M2EVg',
                    'good_publisher' => '18mURBpNZI',
                    'good_price' => 67842,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'YY0Jvb',
                    'good_producer' => 'y1zcwJdXGr',
                    'good_publisher' => 'XynsDaDxwY',
                    'good_price' => 96183,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'oAhgIO',
                    'good_producer' => '3YdUd3S3L9',
                    'good_publisher' => 'AYvXE7Yv5j',
                    'good_price' => 58469,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'oCgkTY',
                    'good_producer' => 'Nb4O7CR9pY',
                    'good_publisher' => 'EiEll70Ukg',
                    'good_price' => 96248,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'koh2bS',
                    'good_producer' => 'VE8DVm0VNC',
                    'good_publisher' => 'LeTWJWLvSm',
                    'good_price' => 40166,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'mScsc6',
                    'good_producer' => '9MKnL6Me4u',
                    'good_publisher' => 'BCvZaWaspx',
                    'good_price' => 79467,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'YTraId',
                    'good_producer' => 'lhZlql4hpR',
                    'good_publisher' => 'cPA3n2bj2s',
                    'good_price' => 24752,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'y53PWt',
                    'good_producer' => 'LsRfHfruoE',
                    'good_publisher' => 'coLmn3VY2J',
                    'good_price' => 729,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'r5smgl',
                    'good_producer' => 'vHtOsCxa2n',
                    'good_publisher' => 'lvQvSYgxpi',
                    'good_price' => 61199,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'quMhe9',
                    'good_producer' => 'rUtvdW3ikE',
                    'good_publisher' => 'G4sHCFkCvd',
                    'good_price' => 51629,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'sgKat3',
                    'good_producer' => 'Ad26mfEnfD',
                    'good_publisher' => 'b2zhh3YgCb',
                    'good_price' => 31310,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'mgYntk',
                    'good_producer' => 'QJJ6QxeUrt',
                    'good_publisher' => 'R8xWEjifOP',
                    'good_price' => 17142,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'EpW0J4',
                    'good_producer' => '2ie1aGyex5',
                    'good_publisher' => '07tUJeiYE6',
                    'good_price' => 21548,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'h1baPw',
                    'good_producer' => 'WuBBwyDztL',
                    'good_publisher' => 'siwP5yUue8',
                    'good_price' => 49774,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'eMdVjZ',
                    'good_producer' => '67pzRvEpR3',
                    'good_publisher' => 'YbislK32aq',
                    'good_price' => 52700,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'M0eSv6',
                    'good_producer' => 'mU45p0igLv',
                    'good_publisher' => 'shlpmWOCOn',
                    'good_price' => 95091,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'QuDYki',
                    'good_producer' => '2WOSxRGM7r',
                    'good_publisher' => 'Uicxi8e6LZ',
                    'good_price' => 55751,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'RzprZX',
                    'good_producer' => 'NE5r8MGaGk',
                    'good_publisher' => 'WlMYtZOLJP',
                    'good_price' => 49924,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'VuRVir',
                    'good_producer' => 'DHzmSNJttY',
                    'good_publisher' => 'wFrY7bBNzc',
                    'good_price' => 61160,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '3v4a0L',
                    'good_producer' => 'HrmH99HU63',
                    'good_publisher' => 'za9aRMVnuQ',
                    'good_price' => 91124,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'M9ZAQN',
                    'good_producer' => '9AVaqiBnBq',
                    'good_publisher' => '6linKdQQNE',
                    'good_price' => 83038,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'iV3kXf',
                    'good_producer' => 'ASgG7zoc3W',
                    'good_publisher' => '1iFKAfhOnP',
                    'good_price' => 77912,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'nIbB5Y',
                    'good_producer' => 'cMDtPytp1z',
                    'good_publisher' => 'E1VXyTvc8J',
                    'good_price' => 16635,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'BbPg9n',
                    'good_producer' => '4ludwuvvuL',
                    'good_publisher' => '7askyw5eqi',
                    'good_price' => 70147,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'O1GGxn',
                    'good_producer' => 'OzuKLe0QNo',
                    'good_publisher' => 'GIdbpvntp7',
                    'good_price' => 92472,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'NuqsAV',
                    'good_producer' => 'kOyNuiNhxG',
                    'good_publisher' => '9Jrz77u1DB',
                    'good_price' => 97547,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'MXjNL6',
                    'good_producer' => 'ifvx7KF1HU',
                    'good_publisher' => 'yacMjPhVry',
                    'good_price' => 38155,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'XzcuGv',
                    'good_producer' => 'DuU6uRJ2PN',
                    'good_publisher' => '3iAMDDvYq3',
                    'good_price' => 69665,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'X4QLut',
                    'good_producer' => 'hUQDmRknPe',
                    'good_publisher' => 'zuSRWkSvVR',
                    'good_price' => 991,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'zP5G2c',
                    'good_producer' => 'lRG5SCrjaE',
                    'good_publisher' => 'UpiXfiOGhb',
                    'good_price' => 1790,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'QRxDD9',
                    'good_producer' => 'mkCvYaVcmM',
                    'good_publisher' => '30OjTvhVqn',
                    'good_price' => 41211,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'yqR3bL',
                    'good_producer' => 'LaB9HfwFND',
                    'good_publisher' => '953Rzd86En',
                    'good_price' => 70395,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'RpWdE5',
                    'good_producer' => 'gO75A0pSbu',
                    'good_publisher' => 'DE39U1CrJc',
                    'good_price' => 52796,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'LqvNyf',
                    'good_producer' => 'OwAE7yFSv1',
                    'good_publisher' => '77v0gcHHv6',
                    'good_price' => 81856,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'oHhyfB',
                    'good_producer' => 'HXRF7H2uwg',
                    'good_publisher' => 'BlE2quU6Fi',
                    'good_price' => 61661,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'OdXqos',
                    'good_producer' => 'aifRCeWpDG',
                    'good_publisher' => '1QuIMGMuGs',
                    'good_price' => 40198,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '1zRQD6',
                    'good_producer' => 'o9QQ53QqOw',
                    'good_publisher' => 'TQSVLpvk8N',
                    'good_price' => 99199,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'sOM4g9',
                    'good_producer' => 'onDCkfthEF',
                    'good_publisher' => '7QbBvuqwA7',
                    'good_price' => 19703,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'enuCpc',
                    'good_producer' => '97ZW1CB0MS',
                    'good_publisher' => 'Jzx1gA6SPq',
                    'good_price' => 72818,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'hmIRUf',
                    'good_producer' => 'kvG4lpt58y',
                    'good_publisher' => '4dCS9nvsaO',
                    'good_price' => 35621,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'ms59V7',
                    'good_producer' => 'RRt7Htwtlw',
                    'good_publisher' => 'jFr4iJxvlG',
                    'good_price' => 83787,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'yRGRb3',
                    'good_producer' => 'KVZRiAr7XT',
                    'good_publisher' => 'XDCwB6ntiZ',
                    'good_price' => 20544,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'Gx4whq',
                    'good_producer' => 'Riqtqt0Pza',
                    'good_publisher' => 'Co9idPgYV7',
                    'good_price' => 44659,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'yi7oQS',
                    'good_producer' => 'hMQeYMKn3v',
                    'good_publisher' => 'bNI0yUz434',
                    'good_price' => 18378,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'j7YvpX',
                    'good_producer' => 'iqMr3EuR68',
                    'good_publisher' => 'DvAfS0KuUQ',
                    'good_price' => 49780,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'hfOBX5',
                    'good_producer' => 'tTe0PaNYuB',
                    'good_publisher' => '6lklfMlAvE',
                    'good_price' => 61655,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '2hqXNM',
                    'good_producer' => 'JtnoodqEHJ',
                    'good_publisher' => 'SeMQrv8kSI',
                    'good_price' => 13742,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'iSjpVB',
                    'good_producer' => 'YTNQWrtVAi',
                    'good_publisher' => '0ztJLQC81u',
                    'good_price' => 38447,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'Zhvlnw',
                    'good_producer' => 'S9iPxfcTci',
                    'good_publisher' => 'zjXPXb0UoA',
                    'good_price' => 70785,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'Ytwxut',
                    'good_producer' => '5fDuspHjHz',
                    'good_publisher' => 'oD7qLTJUw5',
                    'good_price' => 11686,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'PnkpPY',
                    'good_producer' => 'DJ92TFhhhO',
                    'good_publisher' => 'MrSIkTYAXs',
                    'good_price' => 14942,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'OHg0td',
                    'good_producer' => 'zgBKeynd2X',
                    'good_publisher' => 'CUuWb7Wb0T',
                    'good_price' => 20982,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '4ZInmb',
                    'good_producer' => 'BxxFIvrSWX',
                    'good_publisher' => 'c6ZjY0SsCu',
                    'good_price' => 97942,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'vgeg2i',
                    'good_producer' => 'e3NvJXxlsW',
                    'good_publisher' => '3Ii6pDAs0u',
                    'good_price' => 92282,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'XUrqZv',
                    'good_producer' => 'zXA7ha4Utb',
                    'good_publisher' => 'xMWDBTOm6z',
                    'good_price' => 41751,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'gl0Aeh',
                    'good_producer' => 'tHyJWHMIL4',
                    'good_publisher' => 'WDmdxYe37j',
                    'good_price' => 35093,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'qM3DpT',
                    'good_producer' => '4yGxV1WZKk',
                    'good_publisher' => 'qUPRH1OTMC',
                    'good_price' => 90132,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'jbdEJt',
                    'good_producer' => 'jSotvppx28',
                    'good_publisher' => 'siAEmrKE6r',
                    'good_price' => 72599,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '1OlFXX',
                    'good_producer' => 'lmreZRjkiS',
                    'good_publisher' => 'voXkoPx0oB',
                    'good_price' => 6575,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '7OMvr6',
                    'good_producer' => 'JdpwTDoVTW',
                    'good_publisher' => 'PyOSta4BCs',
                    'good_price' => 44892,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'PfbQRB',
                    'good_producer' => 'vvxShDM8IK',
                    'good_publisher' => '2HKXWKhsqm',
                    'good_price' => 32649,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'mU3qtw',
                    'good_producer' => 'bxzLZoAZSG',
                    'good_publisher' => 'p0dUz1aS3V',
                    'good_price' => 26132,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '3gyf7v',
                    'good_producer' => 'nlUgokwQtN',
                    'good_publisher' => 'v8lTA9HlbN',
                    'good_price' => 96525,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'wCCvR5',
                    'good_producer' => 'UUbKiJ9emm',
                    'good_publisher' => 'EhfBDih6EA',
                    'good_price' => 83944,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'DqEFSL',
                    'good_producer' => 'ss4S6T3kQb',
                    'good_publisher' => 'hG16T1yYCS',
                    'good_price' => 28418,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'kZevqN',
                    'good_producer' => 'ap1i3267NZ',
                    'good_publisher' => '1EJNi18386',
                    'good_price' => 68226,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'ZFO0YR',
                    'good_producer' => 'evvOFdJBAy',
                    'good_publisher' => 'Nmk5tRReTC',
                    'good_price' => 23515,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'fYQiey',
                    'good_producer' => 'jqiSQ1qFxl',
                    'good_publisher' => 'iel9k7LQp7',
                    'good_price' => 63707,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'Q0G6KS',
                    'good_producer' => 'iYDLrGXU7i',
                    'good_publisher' => 'nWfc2wVeIG',
                    'good_price' => 21094,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '0DiveZ',
                    'good_producer' => 'CMrnVP8YjU',
                    'good_publisher' => 'tG53pPfupu',
                    'good_price' => 69300,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'UfIwZY',
                    'good_producer' => 'SUb4MhuyFA',
                    'good_publisher' => 'CQAst5usSe',
                    'good_price' => 17518,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'aTE2wO',
                    'good_producer' => '45f0eKgmjK',
                    'good_publisher' => 'EBcMtnjuLH',
                    'good_price' => 24977,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'zFbfkN',
                    'good_producer' => 'sYPFZC61PU',
                    'good_publisher' => 'm0wWvwsreD',
                    'good_price' => 52099,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'SXXZ6Z',
                    'good_producer' => 'aQ9t5Hnlkt',
                    'good_publisher' => 'o2fqoKwXDA',
                    'good_price' => 34395,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'yRyqSb',
                    'good_producer' => 'tOqHDhbGkL',
                    'good_publisher' => '3ykKjnMP84',
                    'good_price' => 60612,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'JPl8oN',
                    'good_producer' => 'dpmM8j4Xte',
                    'good_publisher' => 'FHUv4gkF3x',
                    'good_price' => 56369,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'lhYM8o',
                    'good_producer' => 'sOBkuWVflq',
                    'good_publisher' => 'PVNdK4ZMaQ',
                    'good_price' => 99864,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'TQ6QU7',
                    'good_producer' => 'udzaQ7daS0',
                    'good_publisher' => 'CgltDyUlYt',
                    'good_price' => 22722,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'BGMqu5',
                    'good_producer' => '5JP4zICUAw',
                    'good_publisher' => 'obuZABTOaG',
                    'good_price' => 15652,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'WFUaKj',
                    'good_producer' => 'gXqF0ZYp3p',
                    'good_publisher' => 'ngOBqVcc6K',
                    'good_price' => 21148,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'ECvL27',
                    'good_producer' => '4z47X2mvWX',
                    'good_publisher' => 'gt8Pf4ja9Q',
                    'good_price' => 50094,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'WhlIo8',
                    'good_producer' => 'SYcIP3io0B',
                    'good_publisher' => 'Zfuqd3II1S',
                    'good_price' => 98973,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'KCoayb',
                    'good_producer' => 'NXwEpdDk5M',
                    'good_publisher' => 'cfoCUtFiYI',
                    'good_price' => 63989,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'lmTThZ',
                    'good_producer' => '7vc3mjjagE',
                    'good_publisher' => 'yAroMUwSWa',
                    'good_price' => 92,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'tiEWcn',
                    'good_producer' => 'qrGe0lPFhW',
                    'good_publisher' => 'a7Z2pK4jWp',
                    'good_price' => 11284,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '7g9CG5',
                    'good_producer' => 'iW9AvvA8Dt',
                    'good_publisher' => 'I1b5FoQWpq',
                    'good_price' => 29668,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'yXhChM',
                    'good_producer' => '3ybjMlb8un',
                    'good_publisher' => '5royCIWRW2',
                    'good_price' => 70180,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'k2YWpu',
                    'good_producer' => 'coARDAhan9',
                    'good_publisher' => 'PFZJKcui2t',
                    'good_price' => 9638,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'D2ijNQ',
                    'good_producer' => '8KzUnE6R56',
                    'good_publisher' => 'oTmyngMpMJ',
                    'good_price' => 29485,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'YLfDg8',
                    'good_producer' => '9rdaB7fBje',
                    'good_publisher' => 'nE19L9EzZs',
                    'good_price' => 44193,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '1AeuC6',
                    'good_producer' => 'tlTQV7zMWM',
                    'good_publisher' => 'ExNANCAFzA',
                    'good_price' => 39704,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => '8cyJSj',
                    'good_producer' => 'XZC4hlOIiR',
                    'good_publisher' => 'fhmeobjunB',
                    'good_price' => 58710,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'CTFeGz',
                    'good_producer' => 'TMOKcx6bKM',
                    'good_publisher' => 'YysHnUJdwN',
                    'good_price' => 66679,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'vpMgvz',
                    'good_producer' => 'eaB7h240pG',
                    'good_publisher' => 'cjcyJpWdfW',
                    'good_price' => 91999,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'FNqtDk',
                    'good_producer' => 'A65ivLplka',
                    'good_publisher' => 'fK48he76Sz',
                    'good_price' => 29811,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'sglNrg',
                    'good_producer' => 'Juy4g1FH78',
                    'good_publisher' => 'BNZIQFr0OD',
                    'good_price' => 28805,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'zNSuvo',
                    'good_producer' => 'SZar8dlOP9',
                    'good_publisher' => '8ymv0hZnWE',
                    'good_price' => 95448,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'dTLnUf',
                    'good_producer' => 'CfvK8fVQHd',
                    'good_publisher' => 'VrATxdjAf8',
                    'good_price' => 30762,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'agHHVQ',
                    'good_producer' => 'Xa3miU63Qj',
                    'good_publisher' => 'OBIVIiCWew',
                    'good_price' => 63789,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'XGhrUI',
                    'good_producer' => 'NnqGjIwLAA',
                    'good_publisher' => '3YJEqK4aOw',
                    'good_price' => 31648,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'iKs5L0',
                    'good_producer' => 'Ronb5M2EVg',
                    'good_publisher' => '18mURBpNZI',
                    'good_price' => 67842,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'YY0Jvb',
                    'good_producer' => 'y1zcwJdXGr',
                    'good_publisher' => 'XynsDaDxwY',
                    'good_price' => 96183,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'oAhgIO',
                    'good_producer' => '3YdUd3S3L9',
                    'good_publisher' => 'AYvXE7Yv5j',
                    'good_price' => 58469,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'oCgkTY',
                    'good_producer' => 'Nb4O7CR9pY',
                    'good_publisher' => 'EiEll70Ukg',
                    'good_price' => 96248,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'koh2bS',
                    'good_producer' => 'VE8DVm0VNC',
                    'good_publisher' => 'LeTWJWLvSm',
                    'good_price' => 40166,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'mScsc6',
                    'good_producer' => '9MKnL6Me4u',
                    'good_publisher' => 'BCvZaWaspx',
                    'good_price' => 79467,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'YTraId',
                    'good_producer' => 'lhZlql4hpR',
                    'good_publisher' => 'cPA3n2bj2s',
                    'good_price' => 24752,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'y53PWt',
                    'good_producer' => 'LsRfHfruoE',
                    'good_publisher' => 'coLmn3VY2J',
                    'good_price' => 729,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'r5smgl',
                    'good_producer' => 'vHtOsCxa2n',
                    'good_publisher' => 'lvQvSYgxpi',
                    'good_price' => 61199,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'quMhe9',
                    'good_producer' => 'rUtvdW3ikE',
                    'good_publisher' => 'G4sHCFkCvd',
                    'good_price' => 51629,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'sgKat3',
                    'good_producer' => 'Ad26mfEnfD',
                    'good_publisher' => 'b2zhh3YgCb',
                    'good_price' => 31310,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'mgYntk',
                    'good_producer' => 'QJJ6QxeUrt',
                    'good_publisher' => 'R8xWEjifOP',
                    'good_price' => 17142,
                    'picture_path' => 'default.png',
                    'good_category' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'EpW0J4',
                    'good_producer' => '2ie1aGyex5',
                    'good_publisher' => '07tUJeiYE6',
                    'good_price' => 21548,
                    'picture_path' => 'default.png',
                    'good_category' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'h1baPw',
                    'good_producer' => 'WuBBwyDztL',
                    'good_publisher' => 'siwP5yUue8',
                    'good_price' => 49774,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'eMdVjZ',
                    'good_producer' => '67pzRvEpR3',
                    'good_publisher' => 'YbislK32aq',
                    'good_price' => 52700,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'M0eSv6',
                    'good_producer' => 'mU45p0igLv',
                    'good_publisher' => 'shlpmWOCOn',
                    'good_price' => 95091,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'QuDYki',
                    'good_producer' => '2WOSxRGM7r',
                    'good_publisher' => 'Uicxi8e6LZ',
                    'good_price' => 55751,
                    'picture_path' => 'default.png',
                    'good_category' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'RzprZX',
                    'good_producer' => 'NE5r8MGaGk',
                    'good_publisher' => 'WlMYtZOLJP',
                    'good_price' => 49924,
                    'picture_path' => 'default.png',
                    'good_category' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'good_name' => 'VuRVir',
                    'good_producer' => 'DHzmSNJttY',
                    'good_publisher' => 'wFrY7bBNzc',
                    'good_price' => 61160,
                    'picture_path' => 'default.png',
                    'good_category' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

            ]);
    }
}
